const bucketList = [
  'Abseil Down a Waterfall',
  'Air Boat Across an Alligator Infested Swamp',
  'Arrive By Seaplane',
  'Catch a Wave Surfing',
  'Dog Sled',
  'Ride a Zip Line',
  'Eat Fire',
  'Explore a Cave',
  'Flip on a Trampoline',
  'Flyboarding',
  'Get a Tattoo',
  'Go Bamboo Rafting',
  'Go Fat Biking',
  'Hang Glide',
  'Hold a Shark',
  'Indoor Skydive',
  'Jump Off a Cliff',
  'Kite Surf',
  'Navigate a Personal Underwater SUB',
  'Parasail',
  'Play a Game of Paintball',
  'Police Ride Along',
  'Rappel Down a Waterfall',
  'Rappel into a Cave',
  'Ride ATVs',
  'Ride in a Hot Air Balloon',
  'Ride in a Luge',
  'Sail a Boat',
  'Scuba Dive',
  'Skijoring',
  'Skydive',
  'Snowboard',
  'Swim with Dolphins',
  'Swim with Sharks',
  'Swim with Stingrays',
  'Walk a Suspension Bridge',
  'Walk on Hot Coals',
  'Whitewater Rafting',
  'Wrap a Snake Around My Neck',
  'Zorbing',
  'Attend a Rodeo',
  'Bathe an Elephant',
  'Chase a Tornado',
  'Clamming',
  'Climb a Volcano',
  'Climb to the Top of a Tree',
  'Compete in a Frog Jumping Contest',
  'Complete a Horse Jumping Obstacle',
  'Drive Through a Dust Storm',
  'Feed a Crocodile',
  'Feed a Koala Bear',
  'Feed an Ostrich',
  'Herd Cattle',
  'Hike Every Trail at a State Park',
  'Hold a Monkey',
  'Hold a Tarantula Size Spider',
  'Horseback Ride on the Beach',
  'Hug a Redwood',
  'Kiss a Sea Lion',
  'Kiss in the Rain',
  'Make a Snowman',
  'Milk a Cow',
  'Name a Star',
  'Relax in a Natural Hot Spring',
  'Release Baby Turtles into the Ocean',
  'Ride a Horse Bareback',
  'Ride in a Horse & Carriage',
  'Roll in a Huge Pile of Leaves',
  'See a Coral Reef',
  'See the Salmon Run',
  'Shear a Sheep',
  'Shrimping',
  'Sleep in a Stable on a Haystack',
  'Sleep in a Yurt',
  'Sleep in an Igloo',
  'Stand Under a Waterfall',
  'Swim in the Ocean',
  'Swim in an Aquarium',
  'Swim with a School of Fish',
  'Swim with Manatees',
  'Swim with Sea Turtles',
  'Take a Falconry Class',
  'Walk on a Black Sand Beach',
  'Watch a Caterpillar Turn into a Butterfly',
  'Watch the Sunrise & Sunset in one Day',
  'Witness a Solar Eclipse',
  'Whale Watching',
  'Be a Bridesmaid',
  'Be a Maid of Honor',
  'Be Considered a Cougar',
  'Celebrate a Same Sex Wedding',
  'Cover the Bed in Rose Petals',
  'Find my Best Friend from High School',
  'Find Your First Love',
  'Forgive Someone',
  'Get Engaged',
  'Get Married',
  'Go on a Blind Date',
  'Go on a Double Date',
  'Have a Meaningful Conversation With a Stranger',
  'Host a Family Reunion',
  'Kiss a Stranger',
  'Kiss on Top of a Ferris Wheel',
  'Make a New Friend',
  'Meet a Blog Reader in Person',
  'Meet a World Leader',
  'Meet Someone Famous',
  'Meet the President',
  'Organize a Family Portrait',
  'Plan a Date Night with my Spouse',
  'Play Matchmaker',
  'Receive a Fan Letter',
  'Reconnect with an Old Friend',
  'Share a Cab with a Stranger',
  'Sing a Karaoke Duet',
  'Spend Time with a Person From Another Generation',
  'Stay up all Night Talking',
  'Surprise Someone',
  'Tell Dad I Love Him',
  'Visit your Childhood Home',
  'Write a Love Note with Lipstick on the Bathroom Mirror',
  'Write a Thank you Letter to a Company that Treated you well',
];
